#!/bin/bash

google_home="Kitchen"
#google_home="Bedroom mini"

#touch ~/.lbc

#if [[ -f ~/.tr ]]; then rm ~/.tr & touch ~/.lbc
#fi

vol=$(/home/swipe/bin/cast-linux-amd64 --name "$google_home" status | awk -F 'Volume:' '{print $2}' | cut -c3-5)

/home/swipe/bin/cast-linux-amd64 --name "$google_home" media play https://stream.on.revma.com/6wa52xb1pg0uv?direct=false


/home/swipe/bin/cast-linux-amd64 --name "$google_home" volume $vol 
