#!/bin/bash

# Check to see if another instance of this script is running
for pid in $(pidof -x kill_kscreen_if_docked); do
    if [ $pid != $$ ]; then
        echo "[$(date)] : kill_kscreen_if_docked : Process is already running with PID $pid"
        exit 0
    fi
done


# Check to see if HDMI-3 port is connected (laptop docked)
status="$(xrandr | grep "HDMI-2 connected")"

# While $status variable is not empty (HDMI-3 connected) check to see if kscreen is running and then unload it
while [ -n "$status" ];
    do
        #echo docked
#         if pidof -x "$(basename /usr/lib/kf5/kscreen_backend_launcher)" > /dev/null
#         then
#         pidof -x "$(basename /usr/lib/kf5/kscreen_backend_launcher)" | xargs kill
#         fi

        qdbus org.kde.kded5 /kded org.kde.kded5.unloadModule "kscreen" 2>&1 >/dev/null
        sleep 300
    done
